### ISSUE TITLE
There is a bug in condition branch node

### ISSUE THREAD

**Issue by RoyDingZF** [langgenius/dify#11037]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

in this workflow, typing help to get in help mode.
whatever you type, both direct reply nodes will be triggered and respond with the numbers that shouldn't be responded.
![屏幕截图 2024-11-24 200117](https://github.com/user-attachments/assets/a7fdd867-6d32-4263-a86d-7e1cf7a2f84d)
[bug_dsl.yml.txt](https://github.com/user-attachments/files/17893169/bug_dsl.yml.txt)

### ✔️ Expected Behavior

when you type 1, branch 1 will be triggered, and 2, branch 2 will be triggered.

### ❌ Actual Behavior

both branches are triggered in condition node

**Comment by crazywoola** [comment]
I think this can be resolved by adding a variable aggregator node before the template node.

**Comment by Leheng620** [comment]
I also encountered this problem. When there are two or more nodes connect to a if-else node, all answer nodes after the if-else node will be triggered. A workaround is to add a template node before the if-else node so that there is only one node connects to the if-else node.

![image](https://github.com/user-attachments/assets/96c72e7f-64c9-4c44-8845-a8d0c6735523)

**Before:**
![image](https://github.com/user-attachments/assets/2f4f32e6-da72-4c53-9dd8-31265cc44e0f)

**After:**
![image](https://github.com/user-attachments/assets/da63ce34-a91c-4752-97bc-1bde45b285de)

**Comment by yihong0618** [comment]
@laipz8200 @crazywoola This is fixed too
