### ISSUE TITLE
[wenxin] Bad Request Error, 'results'

### ISSUE THREAD

**Issue by dq7532183** [langgenius/dify#11252]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Recall topK and retrieve topK issues

![image](https://github.com/user-attachments/assets/9bc18d7c-3852-4383-ac16-159dc0e99321)

**Comment by yihong0618** [comment]
@dq7532183 its because baidu rerank model topK can not bigger than the documents length.

can you make topK smaller than try it again?
make topK smaller to 1 and give a try
![image](https://github.com/user-attachments/assets/997ad083-3b2e-4b0f-b723-bf0026c346b0)

@laipz8200 I would like to make this better because baidu status_code always 200....the try catch things did not handle the error ....
can I do that?

**Comment by laipz8200** [comment]
@yihong0618 Of course! Feel free to do it!
