### ISSUE TITLE
dify rest api endpoint 

### ISSUE THREAD

**Issue by hkjang** [langgenius/dify#11473]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I think it would be more scalable if openai compatable api and dify's api were developed to have the same endpoint and response.
Please consider it.

```
curl --location --request POST 'https://api.dify.ai/v1/chat-messages' \
--header 'Authorization: Bearer ENTER-YOUR-SECRET-KEY' \
--header 'Content-Type: application/json' \
--data-raw '{
"inputs": {},
"query": "eh",
"response_mode": "streaming",
"conversation_id": "1c7e55fb-1ba2-4e10-81b5-30addcea2276",
"user": "abc-123"
}'
```

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
This conversation has been brought several times before, we offer a application instead of raw api, because we have lots of different things in it's response, such as workflow details and other meta information, They aim to do different things. And we do not have a plan to make it compatiable with OpenAI's response. This would requires a totally new endpoint to do this work instead of replacing the old ones which would make other applications already run in the production breaks.
