### ISSUE TITLE
私有化部署后流式返回结束3m才返回message_end符号

### ISSUE THREAD

**Issue by jiaojinda** [langgenius/dify#1209]
### Dify version

0.3.21

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

postgres 中dify.conversations 和 dify.messages 数据超过300  
使用流式对话  结束后长时间等待返回结束标志message_end

### ✔️ Expected Behavior

无卡顿返回结束标志

### ❌ Actual Behavior

卡顿2~3秒返回
![image](https://github.com/langgenius/dify/assets/20655464/ddade5bb-6594-468a-a7db-1251ea8a94c9)

**Comment by jiaojinda** [comment]
jing

**Comment by jiaojinda** [comment]
经排查源码   ConversationMessageTask中的def init(self)   为PostgreSQL插入dify.conversations 和 dify.messages耗时，
在数据库中对两个表创建Btree索引后问题得到完全解决  对此思考如下，供开发者参考：
1. 初始化脚本中增加索引创建字段
2. 异步执行对两个表格的插入  优先返回结束标志
3. 增加历史小时保存时长限制

**Comment by takatost** [comment]
I guess it might be related to the triggering of the "message_was_created" event. After the event is triggered, a task to generate the conversation title will be executed, which takes some time.
We will change this issue later so that the title generation will be asynchronously called by the frontend after the first message of the conversation is returned, instead of being blocked by the backend. 😊

https://github.com/langgenius/dify/blob/e409895c0215cf8be22d3feb7a9bb490976d67ac/api/core/conversation_message_task.py#L176

**Comment by tonglei856** [comment]
现在message_end返回还是很慢呀，长达4~5秒，请帮忙解决
