### ISSUE TITLE
History of Conversation 

### ISSUE THREAD

**Issue by MostafaAly331** [langgenius/dify#1470]
### Provide a description of the help you need

Hello,
1-I'm experiencing a problem with GPT-3.5. The AI application seems to not remember the information or questions I've previously provided in the conversation history. As a result, I have to re-enter the information each time.
Please tell me how can fix it with gpt3.5 by the way when using gpt 4 working well but need 3.5 to work well also 

2- can you explain me the max token configuration why set it 2/3 of range BTW when I set the fully max token is returned error 
How it is work

**Comment by crazywoola** [comment]
> 1-I'm experiencing a problem with GPT-3.5. The AI application seems to not remember the information or questions I've previously provided in the conversation history. As a result, I have to re-enter the information each time.
Please tell me how can fix it with gpt3.5 by the way when using gpt 4 working well but need 3.5 to work well also

This should act as the same otherwise it's a bug.

> 2- can you explain me the max token configuration why set it 2/3 of range BTW when I set the fully max token is returned error
How it is work

Because each time the tokens you sent equals `max token + prompt token`, if you prompt is super long, you will get overflow, it's a recommend value. But you can set to max if you haven't input any prompt.

**Comment by timur-nocodia** [comment]
How to accsess Conversation history variable?
![image](https://github.com/langgenius/dify/assets/120160081/80693103-3bfd-4a15-83f9-70dd6a95f1fe)
