### ISSUE TITLE
Error 404 was reported when DIFY connected to the chatglm3 model API

### ISSUE THREAD

**Issue by Chencc01** [langgenius/dify#1556]
### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

I had no problem connecting to the chatglm2 API, but I got a 404 error when connecting to the chatglm3 API
![image](https://github.com/langgenius/dify/assets/151104876/1cce5a4c-7a9e-4dbc-80c6-f60c67e6813e)
![image](https://github.com/langgenius/dify/assets/151104876/5a90cd03-2aa3-49da-8ca7-cf95cfbbea7f)

**Comment by crazywoola** [comment]
Thanks for resubmitting this issue. I have already talked to @takatost about this. We are working on finding a solution to the bug.

**Comment by lchustc** [comment]
hello，after you connect to chatglm2，ho does it shows in model list？
Mine is as follows：
<img width="238" alt="image" src="https://github.com/langgenius/dify/assets/27990344/2f52a8f1-ae27-4578-9c9f-70a378bc364e">

**Comment by Chencc01** [comment]
> hello，after you connect to chatglm2，ho does it shows in model list？ Mine is as follows： <img alt="image" width="238" src="https://user-images.githubusercontent.com/27990344/284804734-2f52a8f1-ae27-4578-9c9f-70a378bc364e.png">

Yes, I see the same output as you.

**Comment by lchustc** [comment]
> > hello，after you connect to chatglm2，ho does it shows in model list？ Mine is as follows： <img alt="image" width="238" src="https://user-images.githubusercontent.com/27990344/284804734-2f52a8f1-ae27-4578-9c9f-70a378bc364e.png">
> 
> Yes, I see the same output as you.

If i chat with chatglm2, it seems that dify demo couldn't remember chat history, which means the "history" will be empty list. 
It doesn't have the ability for multi-turn conversations because the history is always empty. Do you have the same problem?
![image](https://github.com/langgenius/dify/assets/27990344/987e1eb6-2ba1-4037-875e-3e973f7f9082)
![image](https://github.com/langgenius/dify/assets/27990344/97595417-6fc6-4830-9166-23b64994223a)
