### ISSUE TITLE
issue when add model from hugging face.

### ISSUE THREAD

**Issue by heatingp** [langgenius/dify#2054]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.6

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1, Successful deployed model on hugging face, with Inference Endpoints, like the pic blow:
![image](https://github.com/langgenius/dify/assets/128213969/7bfcefb3-6e48-45b0-b432-79cc6c594c97)
2. And I connected to Dify successfully by following the steps from:
https://docs.dify.ai/v/zh-hans/guides/model-configuration/hugging-face
3. But meet error when I tried to talk to the model, it said:
Error: TextGenerationStreamResponse.init() missing 1 required positional argument: 'token'
<img width="703" alt="image" src="https://github.com/langgenius/dify/assets/128213969/7207044e-8093-4a0a-97b8-b49763cda50d">
Looking forward to fix it, thanks!

### ✔️ Expected Behavior

Can generate text smoothy

### ❌ Actual Behavior

Error: TextGenerationStreamResponse.init() missing 1 required positional argument: 'token'

**Comment by GarfieldDai** [comment]
<img width="800" alt="image" src="https://github.com/langgenius/dify/assets/28395549/0d4836f3-6d4a-4f9d-8e67-9b94873082d0">
It seems that the return of your model API don't have the parameter of 'token'. This problem is not at Dify. 

- Please check the Huggingface Docs of TGI project. To learn more about the TGI project, please refer to https://github.com/huggingface/text-generation-inference. 

- You also can contact the author of this model to fix this parameter.
@heatingp
