### ISSUE TITLE
加了知识库后，要如何配置提示词才能正确调用知识库，现在提示：上下文内容块缺失，提示词的有效性可能不好

### ISSUE THREAD

**Issue by tigerun** [langgenius/dify#2203]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

加了知识库后，要如何配置提示词才能正确调用知识库，现在提示：上下文内容块缺失，提示词的有效性可能不好

**Comment by 18075717849** [comment]
@StudyingLover @dosu After the Agent's context is bound to the knowledge base, the knowledge base is not retrieved when sending a question. Is it a problem with the prompt word? If it is a problem with the prompt word, how should I modify the prompt word so that every time I send a question, it will go to the context knowledge base? Search

**Comment by Nyoko74** [comment]
同样的问题，请问你解决了吗？

**Comment by Zongse** [comment]
同样的问题，请问大佬解决了吗？

**Comment by Pandaaaa906** [comment]
最终我手动将问题 和 回复存在一个变量里面，然后传给知识库
