### ISSUE TITLE
Agent app is not supported in blocking mode? Why?

### ISSUE THREAD

**Issue by joyjoyyo** [langgenius/dify#2316]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Provide a description of the help you need

I want to use the blocking mode in the agent app.

**Comment by takatost** [comment]
Agent's reasoning time is usually longer, and in most cases, the Blocking mode will directly time out. 
For example, if you use Cloudflare, the connection timeout is only 100s. Many external reverse proxies in enterprise environments may be even stricter, perhaps only 10s. After timing out, it is difficult to locate which layer the problem is in. Enabling Blocking mode may actually bring more problems. 
My suggestion is to directly receive streaming data and temporarily store it in an object, and then output it all at once after it ends.

**Comment by joyjoyyo** [comment]
> Agent's reasoning time is usually longer, and in most cases, the Blocking mode will directly time out. For example, if you use Cloudflare, the connection timeout is only 100s. Many external reverse proxies in enterprise environments may be even stricter, perhaps only 10s. After timing out, it is difficult to locate which layer the problem is in. Enabling Blocking mode may actually bring more problems. My suggestion is to directly receive streaming data and temporarily store it in an object, and then output it all at once after it ends.

Thank you for answering my questions.
