### ISSUE TITLE
大模型外挂知识库上下文关联不强怎么解决

### ISSUE THREAD

**Issue by HuQi1120** [langgenius/dify#3466]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

![image](https://github.com/langgenius/dify/assets/166478185/72a0d0c6-e0ff-403a-9a69-87601ee0de81)
像这种知识库中已经存放的信息，如果后续问题提问到“他...”，大模型就回答不出来该怎么解决？？？

**Comment by fakeboboliu** [comment]
It's caused by the retrieval flow dify currently used.
Dify will try to re-retrieval context for every single prompt, thus losing memory in previous system prompt.
As far as i know, the solution you can do for now is adding a question variable with initial question and use it for retrieval for a better consistency.

**Comment by crazywoola** [comment]
Close due to #1542

**Comment by lins0621** [comment]
This should be a common problem, is there any solution?
