### ISSUE TITLE
Self hosted SSL not working -> here is what needs to be fixed

### ISSUE THREAD

**Issue by bhctest123** [langgenius/dify#368]
Self hosted SSL not working

- [ ] Set up certbot - https://certbot.eff.org/

- [ ] Set up support for SSL in nginx 

Is this possible to handle?

**Comment by crazywoola** [comment]
The answer is yes
You can modify `nginx.conf` [here](https://github.com/langgenius/dify/tree/main/docker/nginx) to accept your own ssl configuration.

**Comment by roberteles** [comment]
Hello @takatost and @crazywoola!

What we were asking is if setting up SSL & https is something you could handle on your side.

We tried adding certbot to the dockerfile & set up nginx to allow https requests, but we ran into a bunch of issues and we know you understand your configs and setup the best.

We also tried taking the responsibility of nginx on our side (and configure things at the server level instead of docker) similarly to #426, but we ran into issues where the app (Dify) wasn't aware of the different docker containers on a network level.
