### ISSUE TITLE
Changes made to frontend not showing up when app run locally using Docker

### ISSUE THREAD

**Issue by aymanzbaig** [langgenius/dify#3986]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Git clone cd docker docker compose up -d
changes to the frontend doesn’t reflect
so we tried running the frontend seperately
cd web && docker build . -t dify-web
docker run -it -p 3000:3000 -e CONSOLE_URL=http://127.0.0.1:5001/ -e APP_URL=http://127.0.0.1:5001/ dify-web
not [foundt.sh](http://foundt.sh/): line 2:
: not [foundt.sh](http://foundt.sh/): line 3:
: not [foundt.sh](http://foundt.sh/): line 4:
: not [foundt.sh](http://foundt.sh/): line 8:
: not [foundt.sh](http://foundt.sh/): line 11:
: not [foundt.sh](http://foundt.sh/): line 12:
./entrypoint.sh: set: line 13: illegal option

### ✔️ Expected Behavior

Changes in css , icons showing up when the app is run.

### ❌ Actual Behavior

Changes made to the front end not reflected when app is composed and run. Started the app using docker compose up -d. Any changes to source code not reflected . Ran the frontend container seperately. This error follows after following the dify doc instructions(https://docs.dify.ai/getting-started/install-self-hosted/start-the-frontend-docker-container) for running the frontend seperately. 
: not foundt.sh: line 2: 
: not foundt.sh: line 3:
: not foundt.sh: line 4:
: not foundt.sh: line 8:
: not foundt.sh: line 11:
: not foundt.sh: line 12:
./entrypoint.sh: set: line 13: illegal option -

**Comment by TinsFox** [comment]
Hey @aymanzbaig,

Do you want to develop the front end locally? The following method may help you

If you need to start the front end separately, you can make some modifications to the docker-compose.yml file, uncomment these two lines. 

https://github.com/langgenius/dify/blob/2fdd64c1b570cf25c1101c51fb012d3cdf3e645c/docker/docker-compose.yaml#L165-L166

If you do not want to expose this port, you need to configure the environment variables of the front-end development environment so that the front-end can access it through the port exposed by Nginx.

https://github.com/langgenius/dify/blob/2fdd64c1b570cf25c1101c51fb012d3cdf3e645c/docker/docker-compose.yaml#L379-L391

And then run `docker-compose down && docker-compose up -d` which will change the backend port Expose the host machine so that the host machine can be used as a query, and then `cd web && yarn && yarn dev` so that you can see the front-end in the development environment when you visit http://localhost:3000/

To save resources, you can delete this. This will not start the front-end production environment.

https://github.com/langgenius/dify/blob/2fdd64c1b570cf25c1101c51fb012d3cdf3e645c/docker/docker-compose.yaml#L267-L283

**Comment by ye-jeck** [comment]
Encountered the same problem, have you solved it?
