### ISSUE TITLE
Issue with Inputs and variables in chatflow.

### ISSUE THREAD

**Issue by santiagoblanco22** [langgenius/dify#4241]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Try to send params the first time and works.
But If I send the second with the conversationId in the payload for refresh the value, not works.
Other thing, in my opinion is a bad idea:
Variables referenced within a node can only be those from preceding process nodes to ensure coherence and avoid duplication.
Maybe I want to save a variable for a future use in the first node. I don't know how to persist variables for use in the next chat iteration :( 

### ✔️ Expected Behavior

You can send inputs params in all messages and save variables.

### ❌ Actual Behavior

Ignore the value of the input in the second message.

**Comment by santiagoblanco22** [comment]
@dosu let me know if you understand the problem.

**Comment by santiagoblanco22** [comment]
@dosu but manage a external storage for a state is a lot of work.

**Comment by iamjoel** [comment]
@santiagoblanco22 Can you describe the specific scenario where this feature is required?

**Comment by ywuanchai** [comment]
Hi, so has this problem been solved or it has a workaround?
Because I'm also facing this issue.

This is my use case,
1. A user starts a conversation with 1st setting via "inputs"
2. Chatbot returns 3 settings
3. The user chooses 3rd setting and asks for generating X based on 3rd setting
4. Pass 3rd setting as "inputs" to Chatbot and generate X, return to the user
5. The user regret and chooses 2nd setting, and asks for generate X based on 2nd setting
6. Pass 2nd setting as "inputs" to Chatbot ...
if fails on step 3 since we cannot override the "inputs"

Is there any solutions for this?

Thanks!

**Comment by crazywoola** [comment]
Sorry, we do not have a plan to change the user's inputs after the conversation is started. The global variable can be done by adding some thrid-party HTTP service such as serverless functions.

**Comment by wuxuehai01** [comment]
> Sorry, we do not have a plan to change the user's inputs after the conversation is started. The global variable can be done by adding some thrid-party HTTP service such as serverless functions.

Hi, do you mean this service?
https://docs.dify.ai/zh-hans/guides/workflow/node/http-request
