### ISSUE TITLE
Implement document dialogue

### ISSUE THREAD

**Issue by iiiusky** [langgenius/dify#4256]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

I use the dialogue function to perform dialogue tasks for individual documents, but I cannot find a place where users can upload documents in the dialog box.

### 2. Describe the feature you'd like to see

The ability to have document conversations like chatDOC,Users can upload a document in the dialog box, and all answers and questions are based on this document.

### 3. How will this feature improve your workflow or experience?

You can directly analyze the document, which will save a lot of time and bring more scenarios for use.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by bighaidao** [comment]
I hope dify can support it quickly

**Comment by thiner** [comment]
Why is this closed. I think this is a common use case. Current knowledge base design is heavily combined with RAG, which is not suitable to this scenario. Instead of upload file in chat window, I suggest to provide a feature that user can select certain files from knowledge base to start the scoped conversation. This design can reuse the documents, prevent from duplicated file processing.
