### ISSUE TITLE
Unable to make http request either in http node or custom tool and return [Errno -3] 

### ISSUE THREAD

**Issue by DavinciEvans** [langgenius/dify#4423]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I make a request to get the data using the http node, it return error `[Errno -3] Temporary failure in name resolution`. this situation also exists in the defined tools. But this site is avaliable in my host using curl. (Test website: http://baidu.com)

http node:

![20240515173458](https://github.com/langgenius/dify/assets/45795384/5bdc84f0-5512-4738-9753-4f8eaf1191d0)

tool:

![20240515173947](https://github.com/langgenius/dify/assets/45795384/513ce6d5-88e7-4bc7-9ca8-6872016fa29b)

### ✔️ Expected Behavior

http return correctly.

**Comment by DavinciEvans** [comment]
thanks, it looks worked! 😄

**Comment by ZeinabRahbar** [comment]
Hi there, I have this error but due to constraints in ourteam server i  can not change general docker stuff as may cause problem for other projects, in this situation what is your advices??? also, in my workflows LLM nodes work i assume they can connect to internet but why HTTP request in workflows does not work all have the same error  <<[Errno -3] Temporary failure in name resolution>> for any http request in my local system i did not have this issue.

**Comment by SpencerKD** [comment]
> thanks, it looks worked! 😄

I have the same problem，but it not works through these steps. I dont know why.
