### ISSUE TITLE
when set VECTOR_STORE: ${VECTOR_STORE:-qdrant} not working 

### ISSUE THREAD

**Issue by autherlj** [langgenius/dify#5792]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.cp middleware.env.example middleware.env
2.set up VECTOR_STORE: ${VECTOR_STORE:-qdrant}
3.docker compose up -d
4.qdrant images not pulling
5.
![image](https://github.com/langgenius/dify/assets/30717333/93c08e5a-ed33-4ab9-a5be-d2d9c9844549)

### ✔️ Expected Behavior

qdrant container should be working

**Comment by guchenhe** [comment]
Hi @autherlj, thank you for the feedback, `docker-compose.middleware.yaml` is intended to facilitate the development of the frontend and backend of Dify, so you shouldn't need to modify the vector database as much. Apologies that the previous configurations and comments may have given the misleading conception that the vector db is configurable within the middleware services. I've since removed these. If you'd like to swap out weaviate for qdrant nevertheless, consider starting the services directly with something like `docker compose -f docker/docker-compose.middleware.yaml -f docker/docker-compose.yaml up -d db redis sandbox ssrf_proxy qdrant`

Hope this helps!
