### ISSUE TITLE
[Cloud] Create new Knowledge Base from Notion - Batch upload limit

### ISSUE THREAD

**Issue by davidphamle** [langgenius/dify#6218]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Cloud

### Steps to reproduce

As a Pro Dify customer:
1. In Knowledge - Click on create knowledge
2. Click on `Sync from Notion`
3. Select a folder
4. Click on `Save and Process`

### ✔️ Expected Behavior

Able to save and process

### ❌ Actual Behavior

Cannot save, error message of 20 batch upload limit appears
![image](https://github.com/user-attachments/assets/b9874f77-8054-495b-a12b-71054daed79f)

**Comment by crazywoola** [comment]
@JohnJyong

**Comment by crazywoola** [comment]
I have checked this setting, we do have a limit on total numbers that can be uploaded. 
Not only for the free tier, but also for team and pro subscription.

**Comment by davidphamle** [comment]
Yeah, but it didn't make sense since with a knowledge base of more than 20
pages, I can't not add the knowledge in or break it down to into smaller
batch to upload

**Comment by crazywoola** [comment]
In order to maintain the stability of our platform services, we previously imposed a limit on the number of batch uploads. We have now adjusted the batch upload limit for paid customers to 50, allowing you to upload up to 50 files/webpage contents simultaneously. We will continue to optimize new solutions to meet customer needs for flexible resource expansion.

Link https://discord.com/channels/1082486657678311454/1263361877157613688
