### ISSUE TITLE
Vertex AI API Key Incorrrect Padding Error

### ISSUE THREAD

**Issue by breynded** [langgenius/dify#6291]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to Discussions.
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Trying to add Google Cloud /  Vertex AI in Model Provider results in Padding Error message

**Comment by kevinz** [comment]
when will this bug be fixed and merged @dosu

**Comment by loudmu** [comment]
this bug has not been fixed yet !

**Comment by n-guzman** [comment]
Hi. I was having the same issue because I was copying the private key inside the JSON file. I managed to configure the Vertex Model by using these settings:

**Project-ID**: your-project-id
**Location**: us-east1
**Service Account Key**: Encode the whole JSON text file to base64 (the file generated in IAM->Service Accounts->Create Service Account->Keys->Add Key->Create New Key-> JSON). You can use Python to do that, or this [website](https://www.base64encode.org/) for instance.
