### ISSUE TITLE
LLM node cannot stopped with ollama

### ISSUE THREAD

**Issue by Eelahne** [langgenius/dify#6493]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/75ba8750-77f9-4f3b-ab3f-7dd4cd4ed7c7)
(ollama v0.2.7 running qwen2-7b on 4090 the 2nd slot, sometimes it just hung and fully occupied like this, for hours)

My workflow is to process long context (over 20K) with tens of LLM nodes iterations. LLM nodes are all on Ollama linux serving, updated with recent several versions of both Ollama and Dify, but the issue has been still there. The process wouldn't hung every time, it took chance like every two or three turns, one of these LLM node would hung. When this happened, it would never response, so the workflow is waiting until the timeout (already set to 3600s), or until I noticed and deleted the Ollama pod.

It was also suspected the issue could be led by Ollama, but i searched issues from both repo, no topic really the same.

### ✔️ Expected Behavior

Expect if there is solution, or anyone experience the same issue as mine

### ❌ Actual Behavior

I manually delete the ollama pod and wait for the restarting, then pray to work through for the next running. Serving the server.

**Comment by Eelahne** [comment]
I am sure it is not because of connection between Dify and Ollama containers, they are both located in the same namespace of k8s, communicating each other without any resistance. FYI, I counted down the chance it happens, every turn including 5 iterations of 13 calls to LLM while every 1 failure out of 3 turns of workflow leads to around 0.5% of such failure possibility. So this seems to be a stability issue, right?

**Comment by laipz8200** [comment]
Could you please provide the runtime logs for Dify at the time the issue occurred? If the workflow ran with an uncaught error, there should be some error information recorded in the logs.

**Comment by Eelahne** [comment]
![image](https://github.com/user-attachments/assets/018a2715-6443-4676-bf1b-3db6c3895f85)
I am suffering this issue right now, guess this is what you want, as you can see, it has been already idle (well GPU utilization shows 311W and fan in 100% speed, not totally idle) for long and nothing recoded into log. How could i jump out? I have to delete the ollama pod by force, so nothing recorded anyway

**Comment by eviltik** [comment]
This issue was closed as "not planned" but it's a **critical bug** affecting production environments.

When using Dify with Ollama (especially with reasoning models like Qwen3 that can hallucinate infinitely in `<think>` blocks), the inability to actually stop a running LLM node leads to:

1. **Resource exhaustion**: Ollama continues generating tokens indefinitely, consuming GPU/CPU resources
2. **Poor user experience**: Users click "Stop" expecting the generation to halt, but it keeps running in the background
3. **No workaround possible**: Since Dify maintains its own HTTP connection to Ollama, external systems cannot interrupt it - only Dify can close that connection

**The root cause**: When the stop API is called, Dify returns success but does NOT close the HTTP connection to Ollama. According to Ollama's behavior, closing the HTTP connection is the signal to stop generation.

Please reconsider reopening this issue. This affects anyone using Dify + Ollama in production.

Related issues: #18481, #29688, #12798
