### ISSUE TITLE
Add support for glm-4-long to zhipuai.

### ISSUE THREAD

**Issue by jianglin1008** [langgenius/dify#6986]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

glm-4-long supports longer contexts.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by ox01024** [comment]
Due to potential issues with the beta version, the maximum length for glm-4-long is currently at 4095 characters. An exception will be thrown if the length exceeds this limit. We are awaiting the official update from ZhiPuai to resolve this issue.  

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/f1cfad1a-39b1-4e0e-9435-9248d278a70e">
