### ISSUE TITLE
Improvement in max value of top_k in the retrieval settings to retrieve even more relevant chunks

### ISSUE THREAD

**Issue by muckthaa-ss** [langgenius/dify#7187]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

The top_k in the retrieval setting is working fine but if I need to retrive context from say 20 chunks, then the top_k value is limited to 10. 
Example,
I need to generate a summary for a chapter of 20 pages and each page is segmented as a chunk. So I need the context of all the 20 chunks in order to generate the summary using the llm. So it should retrieve 20 chunks but the top_k is limited to 10.

How can the max value of the top_k be increased or modified to more than 10?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by nadirvishun** [comment]
in the doc :
```md
It is important to note that even if the model's context window is large enough, recalling too many segments may introduce less relevant content, reducing the quality of the response. Therefore, the TopK parameter for re-ranking is not necessarily the larger, the better.
```
However, many other articles suggest that it's better to retrieve more items in the first stage of top-k search, otherwise the re-ranking will not be effective，link:
- [知识库问答，数据越多效果越好吗？](https://mp.weixin.qq.com/s/TOB8wIhiTsZ8BVB_WANP0w)
  ![image](https://github.com/user-attachments/assets/323c06d7-b34f-44b7-b3cc-898015871e8a)
- [使用繁體中文評測各家 Reranker 模型的重排能力](https://ihower.tw/blog/archives/12227)
  ![image](https://github.com/user-attachments/assets/36b12795-c8c6-42fb-a997-6305b194ab60)

Normally, there should be two topK values: one is the topk1 retrieved from the vector database in the first stage, and the other is the topk2 after reranking. However, the current system only has one, which should be modified later, reference:[Should the top_k in the retrieval stage be greater than the top_n in the reranking stage? For example, top_k=10, top_n=3](https://github.com/langgenius/dify/issues/5025)

now if you use `Self Hosted (Source)`，can change`dify\web\app\components\base\param-item\top-k-item.tsx`
![image](https://github.com/user-attachments/assets/8dd1119a-30bc-409c-bac4-80207d80b1f6)

**Comment by muckthaa-ss** [comment]
Does increasing the top_k value affect the other parameters like the chunk length and the context size of any llm and other features or only it would work fine by modifying the top_k value alone? If so, then how could it be achieved?

**Comment by nadirvishun** [comment]
The number of items retrieved from the vector stores in the first phase is topk, and the number returned from reranking in the second phase is also roughly topk (if no threshold is set). As a result, the number of segments passed to the LLMs will increase, thereby consuming more tokens or potentially reaching the token limit of the LLMs.

**Comment by muckthaa-ss** [comment]
If I need to retrieve more content from the knowledge and fit them in the context of the llm, then how can this be done?

**Comment by nadirvishun** [comment]
Increase the `TopK`，close or decrease the `Score Threshold`

**Comment by muckthaa-ss** [comment]
If I increase the TopK value to 50 and the chunk length to 2000 with no score threshold, then the context of the llm is not using the entire retrieved chunks. It exceeds the context limit of the llm. This has to handled. How can this be done?

**Comment by nadirvishun** [comment]
Therefore, there should be two parameters:
- One is the `topK` retrieved from the vector stores, with a larger number;
- The other is the `topN` for reranking, which can be smaller since it has already been sorted, thus consuming fewer tokens when sent to the large model.

However, the current version does not support this, so:
- modify the source code to change the `topN` parameter passed during reranking.
- the `score threshold` parameter affects the results returned by reranking, so it can be tested whether setting different values can reduce the number of results returned.
- switch to an LLMs that supports long conversations.

**Comment by ismasher2000** [comment]
How to modify the maximum values for topK and topN in a Dify deployment using Docker Compose.

**Comment by nadirvishun** [comment]
Currently, there is no direct way to modify it. You need to modify the source code yourself, then package the image and upload it to an image repository (like aliyun images repository). After that, modify the `docker-compose.yml` file to replace the official image with your own image and restart. 
The source code includes a `Dockerfile`, so packaging it yourself is quite convenient.

**Comment by yinlianggood** [comment]
请教一下，我用docker 部署的dify， 如果我直接修改 top-k-item.tsx 里面的 max 值为 100后， 如何让修改生效

**Comment by nadirvishun** [comment]
> I am not using docker. So is it fine if I modify the max value in top-k-item.tsx alone and will it work fine?

I tested it work fine.

**Comment by muckthaa-ss** [comment]
@nadirvishun I tried updating the top-k-item.tsx ad observed that /apps page itself is not loading now after the change. How could this be resolved?

**Comment by nadirvishun** [comment]
> @nadirvishun I tried updating the top-k-item.tsx ad observed that /apps page itself is not loading now after the change. How could this be resolved?

`npm run build` and `npm run start`

**Comment by lucifer2859** [comment]
> 请教一下，我用docker 部署的dify， 如果我直接修改 top-k-item.tsx 里面的 max 值为 100后， 如何让修改生效

请问你在docker上解决了吗？

**Comment by lucifer2859** [comment]
> Currently, there is no direct way to modify it. You need to modify the source code yourself, then package the image and upload it to an image repository (like aliyun images repository). After that, modify the `docker-compose.yml` file to replace the official image with your own image and restart. The source code includes a `Dockerfile`, so packaging it yourself is quite convenient.

@nadirvishun dify\web\app\components\base\param-item\top-k-item.tsx corresponds to which file in which Docker container

**Comment by nadirvishun** [comment]
> > Currently, there is no direct way to modify it. You need to modify the source code yourself, then package the image and upload it to an image repository (like aliyun images repository). After that, modify the `docker-compose.yml` file to replace the official image with your own image and restart. The source code includes a `Dockerfile`, so packaging it yourself is quite convenient.
> 
> @nadirvishun dify\web\app\components\base\param-item\top-k-item.tsx corresponds to which file in which Docker container

 use the file `dify/web/Dockfile` build your own docker image, then replace the official docker image.
