### ISSUE TITLE
Can we submit conversation without conversation_ID in dify chat api,we need custom some content

### ISSUE THREAD

**Issue by xutengfei** [langgenius/dify#7510]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Can we submit conversation without conversation_ID in dify chat api,we need custom some content.
which params can recieve chat history like[ {user:hi}{assistant: hello},{user: hi}].
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/a954b3ad-23e2-4b67-bbdf-3b53b2e3c54f">

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Yes you can create a new conversation without conversation_id for sure, just leave it as blank will do. 
We need a conversation_id in second messages because we handle the memory stuffs and message roles internally.

We do not have a plan to expose the user message roles for this api, we offer it as a ready application.
