### ISSUE TITLE
After the LLM node in the workflow enables the memory, the subsequent questions will get new content through the knowledge retrieval node again and bring it into the prompt, which will cause the exception when the LLM answers the subsequent questions. How to solve it

### ISSUE THREAD

**Issue by chaoyuezhao1** [langgenius/dify#7574]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

After the LLM node in the workflow enables the memory, the subsequent questions will get new content through the knowledge retrieval node again and bring it into the prompt, which will cause the exception when the LLM answers the subsequent questions. How to solve it
![企业微信截图_1724398404278](https://github.com/user-attachments/assets/9bf62941-5355-41c8-aeb2-7814d155fc50)

**Comment by crazywoola** [comment]
This is an expected behavior, each time you send message to the workflow then every step will be executed. If you want to avoid this situation, you need to use a LLM before the knowledge retrieval node and if/else node to dispatch the behavior.

BTW, this template is requiring document changes. If you want to ask for help, please use discussion instead.
