### ISSUE TITLE
When the content sent or the content answered by the large model contains some specific echarts codes, the application will crash directly

### ISSUE THREAD

**Issue by FamousMai** [langgenius/dify#7832]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. When I use the prompt 'Use ECharts to draw an example: Display pie charts on a map' to generate a chart with a large language model, it produces ECharts JavaScript code similar to the example below. This causes the application to immediately crash. Moreover, every time I click to enter the application, it crashes instantly, rendering the application completely unusable.

2. The second scenario that triggers this bug is when the aforementioned ECharts code is directly sent to the application, which also causes an immediate crash.

```
```echarts
{
  "geo": {
    "map": "china",
    "roam": true
  },
  "tooltip": {},
  "legend": {
    "data": ["Category A", "Category B", "Category C"]
  },
  "series": [
    {
      "name": "City Data",
      "type": "pie",
      "coordinateSystem": "geo",
      "data": [
        {
          "name": "Beijing",
          "value": [116.4074, 39.9042, 30, 20, 10],
          "itemStyle": {"color": "#f18d00"}
        },
        {
          "name": "Shanghai",
          "value": [121.4737, 31.2304, 25, 25, 15],
          "itemStyle": {"color": "#00a0e9"}
        },
        {
          "name": "Guangzhou",
          "value": [113.2644, 23.1291, 20, 15, 25],
          "itemStyle": {"color": "#7cba00"}
        }
      ],
      "label": {
        "show": false
      },
      "emphasis": {
        "label": {
          "show": true
        }
      },
      "radius": "15%"
    }
  ]
}
```
```

![image](https://github.com/user-attachments/assets/a5e79b0f-938f-4360-a267-52e93df9b152)


### ✔️ Expected Behavior

Can chat normally

### ❌ Actual Behavior

Unable to chat normally, and entering the application will crash with the error: Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by crazywoola** [comment]
@zhujinle Can you take a look at this issue?

**Comment by zhujinle** [comment]
We have not registered the json information of China map to the system. You need to modify the code to introduce the China map. See [ECharts Doc](https://echarts.apache.org/zh/option.html#geo.map)
![image](https://github.com/user-attachments/assets/1771eee0-cb7f-40f5-9b61-9ff4d08b9f9a)

Because the code tried to access an undefined object because of the use of an unregistered map, the program crashed. 
![image](https://github.com/user-attachments/assets/a764374a-ddcf-46a7-9a29-73247c69a695)

And because of the problem of session cache, another rendering was performed when refreshing, which led to a new crash. 

The best way at present is to delete cookies from the browser side, thereby disconnecting the link with the session history and preventing the application from rendering again.

ECharts has too many customizable items and there are too many maps that can be imported, I don’t have a very good way to solve the problem of map import. It seems that I can only disable geo syntax or limit chart types?

**Comment by FamousMai** [comment]
Will the system add support for Chinese maps by default in the future?

Can you add a judgment for unregistered maps? Otherwise, the content returned by the big model contains unregistered map json data, and it can't just crash.

**Comment by zhujinle** [comment]
> Will the system add support for Chinese maps by default in the future?
> 
> Can you add a judgment for unregistered maps? Otherwise, the content returned by the big model contains unregistered map json data, and it can't just crash.

As mentioned above, I think ECharts has too many customizable items, and dify is not a project limited to China. Some of the default maps introduced manually may not be comprehensive enough to meet everyone's needs. This will still lead to this problem, and it may also cause too many registrations and affect system loading.

If you have a better on-demand registrations method, welcome to discuss or submit a PR

For the second issue, ECharts will handle numerical errors by itself during testing. I thought it would be the same for other issues, without considering maps and other situations😥. I will open a new PR to add an error boundary.

**Comment by baiyi-os** [comment]
怎样才能百分百的输出echarts图表
