### ISSUE TITLE
The "在此登录" link in the member invitation email is wrong (no domain)

### ISSUE THREAD

**Issue by linchen1987** [langgenius/dify#7941]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

0. i have config `CONSOLE_API_URL`, `CONSOLE_WEB_URL`, `SERVICE_API_URL`, `APP_API_URL`, `APP_WEB_URL` in `.env` file

1. invite member to join team
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/375505ca-92b6-4935-ba8b-0dde44622b43">

2. check email
<img width="839" alt="image" src="https://github.com/user-attachments/assets/89d4400e-399d-4794-9f2e-038b64fc5f26">

3. the link is wrong (looks like no domain name)
`https://mail.qq.com/activate?token=b71e01ea-5024-42bd-830a-425d7dba31a7`

### ✔️ Expected Behavior

the link of "在此登录" is as expected

### ❌ Actual Behavior

the link of "在此登录" is `https://mail.qq.com/activate?token=b71e01ea-5024-42bd-830a-425d7dba31a7`

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/blob/bf63c5d1e3aae2b6ed424255715e8db059e7ea3e/api/tasks/mail_invite_member_task.py#L33-L52

**Comment by zolgear** [comment]
In the `.env` file, the comment for `CONSOLE_WEB_URL` states: "If empty, it is the same domain." While this behavior works for web pages, where the browser automatically completes the domain, it causes issues with HTML emails.

Specifically, when the `CONSOLE_WEB_URL` is left empty in the `.env` file, the invitation emails sent from `mail_invite_member_task.py` and password reset emails from `mail_reset_password_task.py` generate invalid `href` links. These links lack a domain, resulting in broken or unusable links in the email.

### Steps to Reproduce:
1. Leave the `CONSOLE_WEB_URL` field empty in the `.env` file.
2. Trigger the sending of an email (e.g., member invitation or password reset).
3. Check the generated email and notice the invalid `href` attribute in the links.

### Expected Behavior:
When the `CONSOLE_WEB_URL` is empty, the system should correctly populate the `href` attribute with the appropriate domain, similar to how it is handled in the web interface.

**Comment by sukai-cheng** [comment]
i meet the same question, i can't understand that, can you tell the solution clearly ? thans very much

**Comment by zolgear** [comment]
Have you checked the HTML email?  

https://github.com/langgenius/dify/blob/abe5aca3e217a5575dd733cbd9d94e3107e68ea4/api/templates/invite_member_mail_template_en-US.html#L63

If the `{{ url }}` part in the email is `/activate?token=~`, set `CONSOLE_WEB_URL`.

https://docs.dify.ai/ja-jp/getting-started/install-self-hosted/environments#console_web_url
