### ISSUE TITLE
Vertex AI API failed with squid proxy

### ISSUE THREAD

**Issue by tealeeseng** [langgenius/dify#8480]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

DIFY dockers are running with external squid proxy configured on API docker via HTTPS_PROXY environmental parameter. The setup works with Azure GPT models and self hosted llama3.1-8b model under vllm (openAI api compliant).

For gemini-1.5 flash model hosted in google Cloud's vertex AI, the DIFY API docker failed with error message, "[vertex_ai] Server Unavailable Error, 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:142.251.10.95:443: Failed to connect to remote host: Timeout occurred: FD Shutdown" in chatbot App UI.

![Screenshot from 2024-09-16 10-58-31](https://github.com/user-attachments/assets/d4396d46-e11d-4cbd-bd13-38f517df63c4)
  
/

### ✔️ Expected Behavior

chatbot App UI behave normally

### ❌ Actual Behavior

the DIFY API docker failed with error message, "[vertex_ai] Server Unavailable Error, 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:142.251.10.95:443: Failed to connect to remote host: Timeout occurred: FD Shutdown" in chatbot App UI.

**Comment by tealeeseng** [comment]
Tried step 2 with squid proxy yet the same error message, "[vertex_ai] Server Unavailable Error, 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:142.251.10.95:443: Failed to connect to remote host: Timeout occurred: FD Shutdown" shown in chatbot App UI.

**Comment by tomy-kyu** [comment]
In order to access the Gemini API via Squid Proxy, it seems that it is important that Squid Proxy is able to interpret gRPC and is compatible with HTTP/2. If Squid Proxy is not compatible with gRPC, it will not be possible to communicate with the Gemini API/Vertex AI as it is.
However, it seems that REST is used for image uploads in Vertex AI.

In order to communicate with the Gemini API/Vertex AI API using Squid, which does not support HTTP/2, it is necessary to manually change to REST mode. However, it seems that this was not enough for the request processing of Vertex AI.

The following measures have made it possible to use the Gemini API to a certain extent. I will describe them for reference.
The target is the _generate function in api/core/model_runtime/model_providers/google/llm/llm.py.

- Add transport=“rest” to configure (https://github.com/google-gemini/generative-ai-python/blob/8849d4f46010ce4ae68243c4f8a44a138b56598f/docs/api/google/generativeai/configure.md)
- Explicitly set the processing argument stream to be passed to the result variable to False
- Remove the conditional branch when the stream variable is set to True

I hope that these comments will lead to better handling of Dify in the future.
