### ISSUE TITLE
Elasticsearch Index Prefix from Env Variable

### ISSUE THREAD

**Issue by mazlum** [langgenius/dify#8493]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

![image](https://github.com/user-attachments/assets/6c51d99a-d9ef-406a-952d-ae14cd94705f)

Index names have been defined as hard coded. I think it can be determined from env.

Example;

COLLECTION_NAME_PREFIX=dify_

It's important for permissions in Elasticsearch or other databases.

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by tobegit3hub** [comment]
We would like to contribute this.

**Comment by tobegit3hub** [comment]
It is a common method for all datasets including elasticsearch. I'm not sure if we should add new method so that we can generate collection name with prefix.

<img width="670" alt="image" src="https://github.com/user-attachments/assets/9e21a0d9-a1f1-400c-a7b4-6a5baf7b992c">

For elasticserach vector, we may add new config for users.

<img width="902" alt="image" src="https://github.com/user-attachments/assets/6cfda1f5-9069-4e98-b409-0545016af61d">

Could this need your requirement? @mazlum
