### ISSUE TITLE
Multiple OpenAI Token Support

### ISSUE THREAD

**Issue by racerxdl** [langgenius/dify#8832]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- Add two different OpenAI private models with different tokens
- Try run the second one

The thing is that when adding a model you can select an OpenAI Token: 
![image](https://github.com/user-attachments/assets/c4b47675-e6c5-4a3f-9b5f-6cc0f54db00e)

But there is also a "global API token" at the OpenAI Setup.
![image](https://github.com/user-attachments/assets/2c99721f-0779-4826-90db-1319e89b6733)

### ✔️ Expected Behavior

Both work fine. The model uses the selected API token.

Custom models can be on different accounts, and since the Add Model screen requires a token, that token should be used and no the "global one"

### ❌ Actual Behavior

Only the "global" API token is used.

**Comment by crazywoola** [comment]
This is a paid feature, which can be accessed in cloud version. See docs here https://docs.dify.ai/guides/model-configuration/load-balancing.

Also, please use the right template for new features, this is a bug only template.

**Comment by racerxdl** [comment]
Well, thats a bug since the UI actually allows you to use multiple tokens.

**Comment by rlaneth** [comment]
@crazywoola, it’s quite astonishing that this issue has been closed without proper consideration. After reviewing the linked documentation, it's clear this is a **bug** and not something that should’ve been dismissed. I’ve been able to reproduce the issue, so let me break it down for you:

1. @racerxdl **never** mentioned the Load Balancing feature, which, as per the documentation you have referred to, is indeed a paid feature in the cloud version. What he *actually* referred to was the ability to use a custom access token for a specific model, which **is** clearly available in the self-hosted version (as per @racerxdl's screenshots) but is **not** functioning correctly.

2. @racerxdl was right to classify this as a bug and **not** a feature request. It’s not about adding a feature; it’s about fixing one that’s broken.

Maybe we should tag @goocarlos to come take a look since your reading comprehension seems a bit… compromised, @crazywoola. Or hey, here’s an idea: use an LLM to help you interpret these issues if that’s too hard! If this somehow doesn’t get confirmed as a bug, I’ll just fork the project and fix your broken code myself.

**Comment by taowang1993** [comment]
@rlaneth @racerxdl 

Have you guys been able to solve this?
I am having the same issue when trying to Add Model.

https://github.com/langgenius/dify/issues/9138
