### ISSUE TITLE
How to fix Gemini stream mode？

### ISSUE THREAD

**Issue by AAEE86** [langgenius/dify#8998]
@CXwudi 在config_kwargs中设置 
···
config_kwargs.pop("stream", None) 
····
Although it can solve the error reporting problem, it is still not stream output. The code _handle_generate_stream_response seems to have a problem.

_Originally posted by @AAEE86 in https://github.com/langgenius/dify/issues/8678#issuecomment-2391088192_

**Comment by Hisir0909** [comment]
![image](https://github.com/user-attachments/assets/f5b54eba-eb2f-46f7-8f5e-b8fa7cc247a3)
We need to know how the `stream` parameter was initially passed in. I can override this `stream` in the function to fix the `stream=True` case, but when `stream` is `False`, because the external `stream` defaults to `True`, the non-streaming return result won't be displayed.

**Comment by Hisir0909** [comment]
![image](https://github.com/user-attachments/assets/c950e2a5-d6b1-4da9-bb0e-89aedd6326e9)
When I changed the return value of `_handle_generate_response` to also be in stream format, the `stream=False` issue was also fixed.  This indicates that the handling of the return value has a conditional branch based on the `stream` value. However, I'm currently unsure how to pass the original `stream` value to the modified function.

**Comment by Hisir0909** [comment]
```python
    def _handle_invoke_result(
        self, invoke_result: LLMResult | Generator
    ) -> Generator[RunEvent | ModelInvokeCompleted, None, None]:
        """
        Handle invoke result
        :param invoke_result: invoke result
        :return:
        """
        if isinstance(invoke_result, LLMResult):
            return
```
Hmm, okay, I found the place to handle it. They didn't consider the `stream=false` case at all... Even though they require us to have non-streaming handling when adding LLMs, they actually completely ignore the non-streaming return.

**Comment by AAEE86** [comment]
I don't quite understand these. Can you fix this issue? @Hisir0909

**Comment by CXwudi** [comment]
Hi @Hisir0909, I am just adding my one cent here, `_handle_generate_response` has nothing to do when `stream=False`. Based on 
https://github.com/langgenius/dify/blob/7121afdd4426648b99055b7041b5e99bc7b1ad3a/api/core/model_runtime/model_providers/google/llm/llm.py#L217-L220

`_handle_generate_stream_response` is the method handling stream output. However it correctly returns a generator type which really confusing me

**Comment by Hisir0909** [comment]
> Hi @Hisir0909, I am just adding my one cent here, `_handle_generate_response` has nothing to do when `stream=False`. Based on
> 
> https://github.com/langgenius/dify/blob/7121afdd4426648b99055b7041b5e99bc7b1ad3a/api/core/model_runtime/model_providers/google/llm/llm.py#L217-L220
> 
> `_handle_generate_stream_response` is the method handling stream output. However it correctly returns a generator type which really confusing me

What do you mean?  When `stream=False`, is `_handle_generate_stream_response` still being processed here? My current solution is to use a local variable to override the function's `stream` parameter here, because the LLM node always calls it with `stream=True`, while the actual `stream` setting in the YAML configuration is in `model_parameters`.
![image](https://github.com/user-attachments/assets/17d9b15f-9b0c-450f-97c5-723e898942cd)

**Comment by CXwudi** [comment]
I see, my bad. I misunderstood your previous statement

**Comment by Hisir0909** [comment]
@AAEE86  @CXwudi  Please take a look at my submission.  Can it resolve the issue, and are my modifications reasonable? 🐸
