### ISSUE TITLE
duckduckgo_search  occurs 202 Ratelimit error

### ISSUE THREAD

**Issue by leslie2046** [langgenius/dify#9045]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

![图片](https://github.com/user-attachments/assets/64410b1f-71ba-47a0-bbc3-69e0ac3f0c89)

### ✔️ Expected Behavior

could get the search result

**Comment by Cristhianzl** [comment]
Hi @leslie2046,

It looks like the issue you're encountering is related to a search limit in the DuckDuckGo component. This error likely occurs because the usage limit has been exceeded.

You can find more information about these limits in their documentation: [DuckDuckGo Docs](https://duckduckgo.com/duckduckgo-help-pages/aichat/usage-limits/).

Let us know if you have any other questions!

Thank you.

**Comment by leslie2046** [comment]
@Cristhianzl thank you
