### ISSUE TITLE
OpenAI Embedding 使用了未出现在文档中的base64

### ISSUE THREAD

**Issue by VaalaCat** [langgenius/dify#914]
在使用Dify的过程中，我使用GanymedeNil/text2vec-large-chinese构建了一个与OpenAI Embedding API文档兼容的后端API Server，在我其他的应用中很好的运行。但在Dify中观察到请求出现500，抓包发现Dify请求Embedding使用的是类似这样的结构
```json
{
	"input": [[1111,1111,1111,1111,1111],[1111,1111,1111,1111,1111]],
	"model": "text-embedding-ada-002",
	"encoding_format": "base64"
}
```
经过查询资料发现这是OpenAI在文档中未出现的使用方法，https://github.com/EliahKagan/embed-encode
在文档中给出的请求格式是
```json
{
    "input": ["Your text string goes here","123123"],
    "model": "text-embedding-ada-002"
}
```
希望Dify能够支持这种格式，或者给出设置或环境变量让用户选择使用哪种方式

**Comment by takatost** [comment]
https://github.com/openai/openai-python/blob/b82a3f7e4c462a8a10fa445193301a3cefef9a4a/openai/api_resources/embedding.py#L29
I checked the code of the OpenAI python package. Although the parameters are not mentioned in the API documentation, this code represents the default logic of the OpenAI python package. In order to improve performance, if OpenAI removes this parameter, I believe they should include a deprecated warning in the OpenAI python package.

**Comment by VaalaCat** [comment]
I see. But I still hope that Dify can give users the ability to choose the embedding mode since Dify is an AI middle platform which this helps Dify compatible to other AI's API.

**Comment by takatost** [comment]
Sure, we've added it to the roadmap. We'll make the base64 configuration an optional setting.

**Comment by deepslit** [comment]
> Sure, we've added it to the roadmap. We'll make the base64 configuration an optional setting.

Is it an option now? Met the same problem.
