### ISSUE TITLE
Expand more datasets APIs

### ISSUE THREAD

**Issue by glacierck** [langgenius/dify#9163]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I am trying to modify my file system to achieve automatic synchronization between the document system and dify datasets API. But I found that the design of the datasets API did not fully open up the interface for operations on the dataset and document objects. For example, there is no API specified for querying the dataset based on UUID ('/console/api ' exists). Or, what factors are taken into account to perform interface castration on these objects?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
Here is a pr for hit-testing https://github.com/langgenius/dify/pull/8477, however the author is not responding, you can pick it up if you are interested.

> what factors are taken into account to perform interface castration on these objects?

- We offer a different endpoint to end users/developers instead of making it a general api used in our application, if so, there is no reason to use our datasets UI at all. So keep in mind the API(/console/*) for dify itself is different from the api for the developers.

- We do not have time at that period as well :)
 
If you are interested in implementing more api endpoints, you are always welcome.

**Comment by glacierck** [comment]
@crazywoola good job! Oh, I see！
