### ISSUE TITLE
Whether to consider allowing sys.files uploaded by users at the start node to be passed to other nodes in the workflow

### ISSUE THREAD

**Issue by lem1272536013** [langgenius/dify#9405]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Now I have a problem, when I create an application, I want to add the large model node that is called later based on whether sys.files is null or not, when sys.files is null, call the non-visual model, and when sys.files is not empty, call the visual model, I think this can be done with more flexibility. But the current dify can't implement this feature, so I'd like to ask if you consider opening the sys.files variable to other nodes in the future, such as if conditional nodes. Or is there another way to implement this idea of mine now? thanks

![a188c90a147a371f0cf04a76eed9639](https://github.com/user-attachments/assets/f0134572-098f-4b62-895d-d3c60c40c2c7)

### 3. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by crazywoola** [comment]
From v0.10.0 we will support interacting with the files, however please read things below. Current is https://github.com/langgenius/dify/releases/tag/0.10.0-beta3

Original Node Enhancement
- Start: Custom form items within the start node now include single file and file list types, allowing users to input file types through the start form.
Explanation of usage for system variable sys.file and custom variable file (to be added)
- LLM: Models with vision capabilities can accept file variables (usually image types) to input user-uploaded or externally downloaded image files into models with image recognition abilities for understanding or interpretation.
- Question Classifier: Models with vision capabilities can accept file variables (usually image types) to input user-uploaded or externally downloaded image files into models with image recognition abilities to assist in question classification.
- Parameter Extraction: Models with vision capabilities can accept file variables (usually image types) to input user-uploaded or externally downloaded image files into models with image recognition abilities to assist in parameter extraction.
- Variable Aggregator: Can select File and Array[File] types as input variables for variable aggregation.
- Conditional Judgment (IF/ELSE): Can select File and Array[File] types as conditional input variables. Also supports selecting file properties (such as filename, file size, file type, etc.) as judgment conditions.
- Iteration: Can select Array[File] type as input variable, and output as Array[File] after completing iteration processing.
- HTTP Request: Request body adds binary type, supporting file sending in binary format; form-data adds support for files, allowing key-value pairs of files and text in form data, with specific options defined in Key and Value.
- End: Can select file variables as output.
- Answer: Can select file variables as output.

New Node Support
- Document Extraction Node: Used to parse user-uploaded documents into text content that is easily understood by LLM.
Since LLM cannot directly read or interpret document content, it's necessary to parse user-uploaded documents into text before passing the content to LLM. The document extraction node supports parsing and extraction of mainstream document formats.
Supported formats: TXT, MARKDOWN, PDF, HTML, XLSX, XLS, DOCX, CSV, EML, MSG, PPTX, PPT, XML, EPUB.
- List Filter: Used to filter or sort files uploaded in batch by users. Judgment conditions include: existence, format type, filename, size, etc.
File upload supports batch upload of multiple format files, and the input of the list filter is a file list. When users upload multiple files at once during a chat, the list filter can filter the format type, filename, and size of files to achieve precise control over different file processing flows.

**Comment by tounh** [comment]
直接使用{{#sys.files#}}粘帖到对应的输入框即可。
