### ISSUE TITLE
Documentation/Roadmap for self-hosted Model providers

### ISSUE THREAD

**Issue by nitrag** [langgenius/dify#97]
I appreciate the self-hosted ability of this application, thank you for providing this. Can you please provide some documentation, or explanation here, for the requirement to use third-party hosted models? Is it because they provide an API interface that allows for the scalability of this application? Would it be possible for a user to download and host an open-source model themselves? Is that within the (future) scope of this application to interface with a local model? If not, could you provide some insight on the requirements this application would need in order to interface with local models? Overall, I'm unaware of the limitations of a fully self-hosted solution and perhaps you can shed some light on that.

**Comment by crazywoola** [comment]
Hello @nitrag we do plan add more models in the future, this is on our scope, because we are designed to be a general purpose platform for all kinds of models.  Currently we need more time to implement some other features right now.
We haven't yet tried some third party models right now, but we are working on it, otherwise you will need to fork the repo and modify the backend code a lot.
